import '@/assets/styles/globals.css';
export const metadata = {
    title: 'PP NextJS',
    description: 'Generated by create next app',
    keywords: 'RENTAL Property, Property, Rental, PP NextJS',
    description: 'find the best rental property',
}
const MainLayout = ({ children }) => {
    return (
    <html>
        <body>
            <main>
                {children}
            </main>
        </body>
    </html> );
}

export default MainLayout;