import '@/assets/styles/globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import AuthProvider from '@/components/AuthProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { GlobalProvider } from '@/context/GlobalContext';
import 'photoswipe/dist/photoswipe.css'

export const metadata = {
    title: 'PP NextJS',
    description: 'Generated by create next app',
    keywords: 'RENTAL Property, Property, Rental, PP NextJS',
    description: 'find the best rental property',
}
const MainLayout = ({ children }) => {
    return (
    <AuthProvider>
    <GlobalProvider>
    <html>
        <body>
            <main>
                <Navbar />
                {children}
            </main>
            <Footer />
            <ToastContainer />
        </body>
    </html>
    </GlobalProvider>
    </AuthProvider> );
}

export default MainLayout;