import '@/assets/styles/globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import AuthProvider from '@/components/AuthProvider';

export const metadata = {
    title: 'PP NextJS',
    description: 'Generated by create next app',
    keywords: 'RENTAL Property, Property, Rental, PP NextJS',
    description: 'find the best rental property',
}
const MainLayout = ({ children }) => {
    return (
    <AuthProvider>
    <html>
        <body>
            <main>
                <Navbar />
                {children}
            </main>
            <Footer />
        </body>
    </html>
    </AuthProvider> );
}

export default MainLayout;